AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'storage/**/*'
    - db/schema.rb

# Offense count: 4
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 30

# Offense count: 3
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 361

# Offense count: 2
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 7
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 16

# Offense count: 2
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 1
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
# Offense count: 48
Style/Documentation:
  Exclude: 
    - 'config/**/*'
    - 'app/models/**/*'
    - 'app/helpers/*'
    - 'app/inputs/*'
    - 'app/controllers/**/*'
    - 'app/decorators/**/*'
    - 'test/**/*'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

# Offense count: 1
Lint/MissingSuper:
  Exclude:
    - 'config/initializers/net_http.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/models/currency.rb'
    - 'app/models/market.rb'
Style/StringConcatenation:
  Enabled: false

# Offense count: 13
# Configuration parameters: MaxUnannotatedPlaceholdersAllowed, IgnoredMethods.
# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  Exclude:
    - 'app/models/trade.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Exclude:
    - app/models/trade.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb
  Max: 160

# Offense count: 1
Style/MissingRespondToMissing:
  Exclude:
    - 'app/decorators/member_decorator.rb'

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/models/currency.rb'
    - 'app/models/order.rb'
