defaults: &defaults
  # Если курс принимаемой заявки отличается от текущего более чем на этот процент,
  # то ставим новый курс
  max_incomde_diff_to_suggest: 5

  max_export_records_count: 1000
  default_url_options: &default_url_options
    protocol: <%= ENV.fetch('HTTP_PROTOCOL', 'https') %>
    host: <%= ENV.fetch('LARRY_HOST', 'localhost') %>
  openbill:
    categories:
      system:  a8237d74-e30d-4123-8f26-eda8ba593209
      wallets: a8237d74-e30d-4123-8f26-eda8ba593208
      storno:  a8237d74-e30d-4123-8f26-eda8ba593207
      partners:  a8237d74-e30d-4123-8f26-eda8ba593206

development:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
