# Gera::ExportToBestchangeWorker:
  # cron: '*/15 * * * * *'
  # class: Gera::ExportToBestchangeWorker
  # queue: critical

###
#### Gera
#
# Обновляем раз в 15 минут просто на всякий случай
#
Gera::PurgeCurrencyRatesWorker:
  cron: '27 2 * * *'
  class: Gera::PurgeCurrencyRatesWorker
  queue: purgers

Gera::PurgeDirectionRatesWorker:
  cron: '27 3 * * *'
  class: Gera::PurgeDirectionRatesWorker
  queue: purgers

Gera::CreateHistoryIntervalsWorker:
  cron: '*/17 * * * *'
  class: Gera::CreateHistoryIntervalsWorker
  queue: default

